### ISSUE TITLE
Add rounder border styling to "Catalog your Research"? 

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/InvenioRDM-at-NU#223]
```css
#navbar entry {
  border: 2px solid white;
  padding: 1px 5px 1px 5px;
  border-radius: 4px;
}
```
